# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_Details',
            new_name='order_details',
        ),
    ]
