# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_auto_20181016_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.CharField(max_length=100),
        ),
    ]
